### ISSUE TITLE
Figure out the connectivity problems

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/inbox-by-gmail-checker#12]
There's [several reviews](https://chrome.google.com/webstore/detail/inbox-by-gmail-checker/mpjmeeikbbgccbjkbfabocnjcaejdpmj/reviews) that say that the extension remains gray like it can't connect. This issue is dedicated to figuring out why.

**Comment by fedexcain** [comment]
Hey, I seemingly have this issue on Google Chrome Version 48.0.2564.103 (64-bit), OS: Arch Linux64. If there's any information/data I can provide you with to resolve this ask away :)

**Comment by joeyespo** [comment]
Hey @FedexCain. Thanks for chiming in here!

I think I figured out the problem. Apparently if you visit `mail.google.com` manually, some auth happens in the browser and all future AJAX request will work. I just published a version that does this (if checking mail responds with `401`). Could you try using `v3.6.0` and let me know if it starts working for you?

Thank you :smiley:

**Comment by fedexcain** [comment]
Hey! 
Sometime in the last 10 days 3.4.0 must have started working for me. Sadly I can't pinpoint when or what I was doing at the time :(. 
However, due to some reasons I had to reinstall Chrome / lost my Chrome profile two times about 2 weeks ago and I distinctly remember that every time Chrome started 'fresh' and synced my plugins, inbox checker would stay grey (even though I tried restarts and other things - that's how I found the bug after investigating).
So I just backed up my Chrome profile (~/.config/google-chrome/), reinstalled Chrome + restart OS and started what should behave like a fresh install of Chrome. After entering my Google profile it started syncing and inbox checker instantly turned from grey to blue so 3.6.0 seems to resolve my issue!

Hope this helps, thanks for the quick fix and the very useful extension!

**Comment by joeyespo** [comment]
@FedexCain Hooray! Thanks for this info, it's helpful. I'll leave this bug open for now (until v4.0 perhaps), and see if I can figure out a good way to reproduce. In the meantime, #15 might help make sure this isn't still happening.

**Comment by joeyespo** [comment]
OK. I was able to reproduce, step through with the debugger, and think I figured out what's going on.

There was a bug in the error handler, causing a loop and mis-reporting it as being in a bad state. That was all refactored and cleaned up, so the v4.3.0 version released just now should be more reliable than previous versions. Anyone, feel free to re-open if this persists and I'll dig deeper.

**Comment by JLopeDeB** [comment]
Hi, I'm using the extension for a week now. I see this issue often. It is solved by restarting the browser but I figured you might find a permanent fix. Other than that I'm super happy happy, thanks a lot.

Browser: Vivaldi 1.10.867.48 (Stable channel) (64-bit)
Chrome/59.0.3071.112

OS: Windows 10 Creators Edition.

Let me know if I can be of any help. Thanks!

Edit: Also, there are times that the icons turns to blue again suddenly, with no apparent reason.
