### ISSUE TITLE
Multiple window opening

### ISSUE THREAD

**Issue by frandzdy** [joeyespo/inbox-by-gmail-checker#16]
I have my extension which open always a new tab window !!

![image](https://cloud.githubusercontent.com/assets/15669629/13248626/b5e7f2de-da1f-11e5-9c7d-85fb66996885.png)

**Comment by pan-long** [comment]
@frandzdy Hi, can I know your chrome version and the url it opens every time?

**Comment by frandzdy** [comment]
Hi, 

My chrome version is Version 48.0.2564.116 m.

And the url it s https://inbox.google.com/ 

I don't know why

I have 2 accounts chrome
But since i delete the plugin in my second account. This don't happen again.
if that can help !!

**Comment by pan-long** [comment]
Hi,
I am not the developer and I am just curious about your problem. I have looked the code and it seems fine. It might be some problem with chrome. We can wait the developer to check it.

**Comment by joeyespo** [comment]
Hi @frandzdy, is this still happening for you?

**Comment by frandzdy** [comment]
Not anymore but i don't know why it's happen so i remove and reinstall the app

**Comment by joeyespo** [comment]
:+1: 

Could have been an older bug. Not sure what it was and not going to dig in right now, so closing. Feel free to re-open if you see it again!

**Comment by joeyespo** [comment]
I _just_ saw this happen when re-installing Chrome. It happened during that awkward phase when you're logged into Chrome, syncing your plugins, but you're not yet logged into Gmail.

Re-opening to remind myself to make `workaroundAttempted` a global variable [instead of a parameter here](https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/background.js#L201). That way we know for sure Gmail will only open once.

Thanks for originally opening this, @frandzdy! I would have written this off as a fluke otherwise.

**Comment by frandzdy** [comment]
Yeah it's happen again damn 

@joeyespo U'r welcome. For a moment, i think i was the only one.

Ok Hope u will fix it !!

**Comment by dolan-a** [comment]
Same issue occurring for me, but only v4.0.0. My already-opened Inbox tab gains focus, but an additional tab is opened without focus each time I click the button.

**Comment by tylorhl** [comment]
@pydolan Same. Looks like it's related to the change from be6059a364d8bc37b1f4960a3917a7cb9c984349. It looks like both queries are being processed regardless of their results, which causes a strange behavior.

For me, if I click, a new tab opens for Inbox. If I click while on that new tab, a new Inbox tab will open.
If I have an Inbox tab and am sitting on a new tab, my Inbox tab will gain focus, my new tab remains unchanged, and no new tab is created.

Since chrome.tabs.query is an asynchronous call, one of the queries can probably just be called in the callback of the other.

**Comment by joeyespo** [comment]
@tylorhl Oops, bad mistake on my end. Looks like I didn't test the case where an Inbox tab was already open. I'll fix this today.

**Comment by joeyespo** [comment]
So this issue began with "inbox tabs keep on opening up" and turned into "an existing Inbox tab is being focused, but a new one is created too" with the release of 4.0.

The latter was fixed in #21 (thanks, @shali3!), and I took this as an opportunity to fix the former using the global variable I mentioned in [an above comment](#issuecomment-224794798).

So closing this issue as "complete" now. Feel free to re-open if either case persists.

**Comment by frandzdy** [comment]
good Thx u
