### ISSUE TITLE
Extension permissions

### ISSUE THREAD

**Issue by Najki** [joeyespo/inbox-by-gmail-checker#23]
This extension is nice. Seems like you've put a lot of effort in the development. But still you ask for a lot of permissions upon installation. I'm talking about the read/write access to `*://*.google.com`. What do you think about changing this to inbox.gmail.com and mail.google.com specifically? I've looked through your code and it seems like you only use these two domains. 

Google provides a lot of services nowadays including wallet, android pay etc. It is a bit unfair to ask for access to all of these services only to display the number of unread e-mails, don't you think?

**Comment by joeyespo** [comment]
Yes, this makes sense 👍 

Would you be up for a PR for the credit? If not, I'll get to it soon.

**Comment by Najki** [comment]
No problem. Here you go https://github.com/joeyespo/inbox-by-gmail-checker/pull/24 😃

**Comment by joeyespo** [comment]
Excellent! Thanks for bringing this up and then owning it 😃

**Comment by joeyespo** [comment]
Just released v4.2.0 with these tightened permissions.

Since you're here, any advice on how to make announcements like permission changes to help explain what they are? I noticed that in [the Support tab](https://chrome.google.com/webstore/detail/inbox-by-gmail-checker/mpjmeeikbbgccbjkbfabocnjcaejdpmj/support), people were assuming that "read and change all google data" was the new permission when it was really "notifications". I'd probably assume the worst too, tbh. (I also don't get emailed when new support tickets are posted.)

No doubt this change will help. So thanks again for the issue and its fix.

**Comment by Najki** [comment]
> I noticed that in the Support tab, people were assuming that "read and change all google data" was the new permission when it was really "notifications".

Yeah. I've thought that too and that's why I visited your project on GH in the first place. I've even checked the history of changes to confirm that the `*.google.com` permission was there from the beginning indeed. Probably it was displayed somewhere in the installation process but it was so long ago that I've forgotten about it.

I use a few extensions and there's only one of them which does some kind of user notification after selected updates - it's Ghostery. But I've gotta say that their notifications are really annoying. They pop up somewhere in the top of your browser and you have to click through them. They are displayed again on next browser launch of you don't finish the process. I find it very annoying.

I personally don't think that you will need another permission change in the closest future so maybe these announcements aren't that necessary? I like to know what was updated and I often check update messages in Google Play, but alerts, pop-ups and modals with this information could not be appreciated by users.

Maybe putting the link to GH or GH releases on the extension page in Chrome Web Store would be enough. Those who are more aware of IT security are someway tech-related and maybe they would be eager to check the releases list on Github. Everything would become clear to them after reading the release notes.

**Comment by Najki** [comment]
But you would have to be more precise with the release notes instead of writing "Set version to 4.2.0" like you did before 😄

**Comment by joeyespo** [comment]
**Update** Looks like "tabs" and "webNavigation" were also making the extension ask for too many permissions on install. I since replaced "tabs" with the less scary "activeTab" and removed "webNavigation" altogether since it was left in mostly for older Chrome versions.

This should further clean up the permissions prompt in v4.3.0.

Thanks again for bringing this up.

**Comment by joeyespo** [comment]
@Najki Also, good suggestion 😃 I just added a link to the CHANGELOG in the Chrome Store description as well.

v4.3.0 is now published. Let me know if there's anything else you can think of to improve the experience!

**Comment by Najki** [comment]
Hey @joeyespo, no further ideas for now but I do reported a bug right now. Check it out at https://github.com/joeyespo/inbox-by-gmail-checker/issues/34
