### ISSUE TITLE
Share to email

### ISSUE THREAD

**Issue by JeremyWW** [joeyespo/inbox-by-gmail-checker#25]
Any chance of adding a 'Share to Email' function that opens up the Inbox Compose window?

**Comment by joeyespo** [comment]
Hi @JeremyWW. Any examples of what you mean that you can point me to (e.g. other extensions)?

**Comment by JeremyWW** [comment]
Yeah, Google's own Inbox extension:

https://chrome.google.com/webstore/detail/inbox-by-gmail/gkljgfmjocfalijkgoogmfffkhmkbgol?hl=en-GB

**Comment by joeyespo** [comment]
Ok, thanks!

I actually think the dropdown design is a disadvantage since most of the time you just want to view your inbox, and this adds friction to that action. Would you be open to a new, completely independent extension that does this? (I share a lot of articles, so this actually appeals to me too.)

**Comment by JeremyWW** [comment]
I agree. How about having it as a right click only option on the toolbar icon and potentially the page right click context menu?

**Comment by joeyespo** [comment]
Oh nice! I was going to say that Chrome didn't offer this feature, [but looks like it does now](http://stackoverflow.com/questions/24295862/adding-drop-down-menu-to-chrome-extension-icon).

Also, I noticed another extension like I described [already exists](https://chrome.google.com/webstore/detail/share-link-via-email/ejdbkikfbnnhmachnnomjfgjbgkcnjkb). So no need to make a new one.

**Comment by JeremyWW** [comment]
Hmm...unfortunately that extension's behaviour isn't too tidy. Although it opens an Inbox compose window it will always open Inbox again regardless of whether you have Inbox open in an existing tab. So, with the default settings it forces Inbox to 'overwrite' the page you're trying to send by email, or you can ask the extension to open a new tab so you end up with duplicate Inbox tabs. Basically it can't recognise an 'existing' Inbox tab. So, I could either try to ask the developer of that extension to correct that behaviour (but then it's 'another' extension to have installed) or suggest that you make a better job of it! :-)

**Comment by joeyespo** [comment]
> unfortunately that extension's behaviour isn't too tidy

Ah, that's a shame. Oh well.

I *could* write a new extension. (Or you could if you're looking for a relatively easy side project 😃). But last night, I did figure out how to do it here, and think it'll be a nice addition. So thank you!

Here's a quick screenshot of the WIP (and a sneak peak at a new upcoming feature)

![share page to inbox screenshot](https://cloud.githubusercontent.com/assets/634573/23492368/076f72bc-fed2-11e6-8407-fecc04f4ed40.png)

Unfortunately, I couldn't figure out how to implement the "Save to Inbox" feature from that extension. That seemed to use an internal API that I'd have to spend much more time stepping through to figure out. (And then hope they don't suddenly change it.) But Inbox does accept the `?subject=&body=` format, so I was able to get this piece working.

What do you think?

**Comment by JeremyWW** [comment]
Not sure the 'Save to Inbox' feature has any use at all, so I'm really not worried. But what is 'Go distraction-free...' ? Nitpicking but I would phrase it 'Share page to Inbox' (rather than 'in' Inbox) - just scans better! Any chance of adding it as a right click context menu entry as well?

**Comment by joeyespo** [comment]
> Not sure the 'Save to Inbox' feature has any use at all

Yeah, it doesn't seem that useful to me either since the browser already offers "bookmarks" for saving links (and services like Pocket exist for reading articles later). But the other extension had this, so I had to mention it here. If anyone does want this feature, the Inbox team may have to open up their API first.

> But what is 'Go distraction-free...' ?

An upcoming [Pomodoro](https://en.wikipedia.org/wiki/Pomodoro_Technique)-inspired feature that lets you work without email distractions for a set amount of time. Like like "Quiet hours" on the options page, this means no notifications and no visible unread count on the icon.

> Nitpicking but I would phrase it 'Share page to Inbox' (rather than 'in' Inbox)

Ok, thanks for the suggestion. I wasn't sure what would sound good. The other extension uses "to" in their *save* feature, and "via" in their *share* feature:

![inbox popup screenshot](https://cloud.githubusercontent.com/assets/634573/23561984/9c3cb7dc-000e-11e7-8f49-5d5d7382cb75.png)

What do you think about "Share page via email" or "Share page via Inbox" instead? Or do you still think "Share page to Inbox" is better?

> Any chance of adding it as a right click context menu entry as well?

Sure. I may make this an option though since browser context menus can get noisy rather quickly.

**Comment by JeremyWW** [comment]
Actually, why not just use the Google phrase 'Share via Email'. It's shorter and says what it means. The nice thing about the context menu is not having to reach for the toolbar button. Just convenient I guess if using it a lot.

**Comment by JeremyWW** [comment]
Any idea when you'll be releasing a new version with this included? Thanks.

**Comment by joeyespo** [comment]
OK. Going with "Share page via email" for both simplicity and clarity. "Share via email" could be misinterpreted as "Share this extension via email" or "Share the current selection via email" (which doesn't sound particularly useful to me).

Context menu is implemented as well, with an option to turn it off.

Release is in progress. Thanks for being patient and for the helpful discussion!

**Comment by joeyespo** [comment]
v4.3.0 was just released! Thanks again, @JeremyWW.
