### ISSUE TITLE
Support for longer poll intervals?

### ISSUE THREAD

**Issue by orschiro** [joeyespo/inbox-by-gmail-checker#7]
Dear @joeyespo,

What a fantastic extension. 

Thank you very much!

I have one question. I set the following setting to check my inbox every 3 hours:

![image](https://cloud.githubusercontent.com/assets/170947/11995275/1e828478-aa4e-11e5-8b31-95b84d751ace.png)

However, it seems that this large number of seconds is not respected. 

The checker does not wait for 3 hours. 

Can you confirm this problem?

Merry Christmas,

~ Robert

**Comment by joeyespo** [comment]
Thanks, @orschiro! :smiley: 

Yeah, it's currently designed to be limited to an hour maximum. So the fact the UI doesn't reflect this is a bug.

However, since you're bringing this up, now's a good time to question whether the limit makes sense. I had it in there because the original implementation did (for exponential backoff). But with the addition of a custom interval, this limit might not make as much sense.

What do you think? To spin the question, what makes you interested in a three hour check instead of a more frequent one?

**Comment by orschiro** [comment]
Dear @joeyespo,

Thank you very much for your elaborated response!

> What do you think? To spin the question, what makes you interested in a three hour check instead of a more frequent one?

My request origins from the desire to limit my own email consumption to only a few times a day. Ideally, I would tools like your extension to support me to check my emails only 3x a day (morning, midday, evening).

Since I have a tendency to check them more often without an effective helper in place, I would like to use your extension to notify me every 3-4 hours about the status of my email inbox. 

What do you think in return?

Warmly,

~ Robert

**Comment by joeyespo** [comment]
Ok cool, thanks for explaining!

I wonder if this is the best method for reducing checks then. There's a number of things that could cause the polling to reset and lead to a unreliable polling schedule. Over time, this may actually make you feel the urge to check _more_ often since, at any given time, the uncertainty implies the checker could fire at any moment within the next three hours. Clicking the button would then reset the checker so it fires again in 3 hours, which would be the only certainty you'd come to expect. (I'm just thinking out loud here, if this is the behavior you're after, then that's fine.)

Perhaps you could try the "quiet hours" feature? I built that specifically to help with productivity by hiding the unread count during specific times of the day. This might reduce email distraction more reliably.

My own schedule is to hide the count in the morning, show it at noon (for an hour), then show it at 5p onward. In my mind, not seeing the unread count keeps me from feeling the urge to check (and sometimes I even miss the window from being productive), and knowing that at 4p I'll have an open window in an hour helps delay the urge and keep on working. (Compare that to a time-relative schedule and spending some brainpower asking "hmm, when was the last time I checked email?") Does this sound helpful at all?

**Comment by orschiro** [comment]
Dear @joeyespo,

I understand your reasoning, thanks!

So, would you suggest something like the following to work for my use case?

```
Quiet hours: 10-13,14-16,18-23
```

> My own schedule is to hide the count in the morning, show it at noon (for an hour), then show it at 5p onward.

If my interpretation of the quiet hours was wrong, can you please show me your implemented example?

Warmly,

~ Robert

**Comment by joeyespo** [comment]
Yes, exactly. It takes a comma-separated list of hours (24-hour style), so your setup would be:

```
Quiet Hours:
10,11,12,14,15,18,19,20,21,22
```

Mine was implemented this way:

```
Quiet Hours:
9,10,11,13,14,15,16,17
```

Out of curiosity, what did you think the quiet hours box did?

Hope that helps.

**Comment by orschiro** [comment]
Dear @joeyespo, 

Thanks for adapting your example to my needs!

I understood what the quiet hours option was supposed to do but didn't understand fully the helping text. 

Maybe you want to add your given example to the helping text to make it more clear that entries have to  be only separated by `,` and not `-` between the hours?

Thanks again for your help! I consider my request solved. :)

~ Robert

**Comment by joeyespo** [comment]
Awesome.

I'll fix the bug of the input box not showing the constraints, and I do plan on later making the quiet hours more intuitive.

Thanks :smiley:

**Comment by orschiro** [comment]
Cool, thanks @joeyespo! :)

**Comment by orschiro** [comment]
Dear @joeyespo,

One last thing I would like to discuss with you.

During quiet hours I find it too tempting and distracting to see the number of unread messages that were fetched during the last non-quiet session. 

Would it be possible to remove the number count during quiet hours or display something instead, e.g. a `Q` for quiet or `Szz...` for sleeping? :)

~Robert

**Comment by joeyespo** [comment]
@orschiro Oh, I like that idea! Could you open a new issue for it? I think it'd make for a good option (probably 'on' by default so people get immediate visual feedback and can turn it off if they don't like it).

Thanks!

**Comment by orschiro** [comment]
@joeyespo,

Great you like it!

There you go with the reference: https://github.com/joeyespo/inbox-by-gmail-checker/issues/9

~Robert

**Comment by joeyespo** [comment]
@orschiro thank you!
